restart-times: 0
jobs: 5000
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 600
rerun-incomplete: True
keep-going: True
printshellcmds: True
